#!/usr/bin/env sh

case $1 in
    'vim')
        cp -i vim/.vimrc ~
        ;;

    'zsh')
        cp -i zsh/.zshrc ~
        cp -i zsh/.zshrc.osx ~
        cp -i zsh/.zshrc.linux ~
        ;;

    *)
        echo 'Usage: ./setup zsh'
        echo '     |         vim'
        ;;
esac


