"-----------------------------------------------------------

set title
syntax on
imap <c-]> <esc>

"-----------------
" Indent
"-----------------
set tabstop=4
set softtabstop=0
set shiftwidth=4
set smartindent
set smarttab 
set showmatch


" Tab -> Space
set expandtab


"-------
" Other
"-------
set clipboard=unnamed
set list
set listchars=tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%

" Color
hi EasyMotionTarget ctermbg=none ctermfg=red
hi EasyMotionShade  ctermbg=none ctermfg=blue

"macvim
if has("gui_running")
    colorscheme desert
endif

" 改行コードの自動認識
set fileformats=unix,dos,mac

"◯とかの文字でカーソルがずれないように
set ambiwidth=double

"----------------------
" ステータスライン関連
"----------------------

set laststatus=2
"set statusline=%<%f\ %m\ %r%h%w%{'['.(&fenc!=''?&fenc:&enc).(&bomb?':BOM':'').']['.&ff.']'}%=\ (%v,%l)/%L%8P\

set display+=lastline "画面最後の行を出来る限り表示する

"行番号を表示
set number
"カーソルの位置を表示
set ruler
"let g:lightline = {
"      \ 'colorscheme': 'wombat',
"      \ 'component': {
"      \   'readonly': '%{&readonly?"⭤":""}',
"      \ }
"      \ }


"--------------------------------------------------------------------------
" neobundle
set nocompatible               " Be iMproved
filetype off                   " Required!

if has('vim_starting')
    set runtimepath+=~/.vim/bundle/neobundle.vim/
    endif

    call neobundle#rc(expand('~/.vim/bundle/'))

    filetype plugin indent on     " Required!

" Installation check.
if neobundle#exists_not_installed_bundles()
    echomsg 'Not installed bundles : ' .
        \ string(neobundle#get_not_installed_bundle_names())
    echomsg 'Please execute ":NeoBundleInstall" command.'
    "finish
 endif

" Plugins
NeoBundle 'vim-fugitive'
NeoBundle 'lightline.vim'

" syntastic
execute pathogen#infect()
